version: 0.2
env:
  variables:
    # https://github.com/cdklabs/cdk-ecr-deployment/issues/478#issuecomment-1938020710
    NO_PREBUILT_LAMBDA: "1"
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm install aws-cdk -g
      - CDK_STACK=$(aws cloudformation list-stacks --query 'StackSummaries[?(StackName==`CDKToolkit` && StackStatus==`CREATE_COMPLETE`)].StackId' --output text)
  build:
    commands:
      - cd ./PetAdoptions/cdk/pet_stack/
      - npm install
      - if [ -z "$CDK_STACK" ] ; then cdk bootstrap ; else echo "Already bootstrapped" ; fi
      - npm run build
      - cdk deploy Services --context admin_role=${EE_TEAM_ROLE_ARN} --require-approval=never --verbose -O ./out/out.json
      - cdk deploy Applications --require-approval=never --verbose -O ./out/out.json
artifacts:
  files: "./PetAdoptions/cdk/pet_stack/out/out.json"
