# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - amg_grafana-identity.yaml
  - amg_grafana-amp-datasource.yaml
  - amg_grafana-dashboard.yaml