# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
spring:
  application:
    name: petstore
cloud:
  aws:
    region:
      static: eu-west-1
      auto: false
server:
  port: 80