{
 "title": "PetAdoptions Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rate of pets adopted vs searched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_petsite_petadoptions_total[15m])/rate(adot_petsite_petsearches_total[15m]))* 100"
    }
   ]
  },
  {
   "title": "Total searches for pets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "adot_petsite_petsearches_total" }
   ]
  },
  {
   "title": "Rate of Puppy searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_petsite_pet_puppy_searches_total[15m])/rate(adot_petsite_petsearches_total[15m]))*100"
    }
   ]
  },
  {
   "title": "Rate of Bunny searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_petsite_pet_bunny_searches_total[15m])/rate(adot_petsite_petsearches_total[15m]))*100"
    }
   ]
  },
  {
   "title": "Rate of Kitten searches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(adot_petsite_pet_kitten_searches_total[15m])/rate(adot_petsite_petsearches_total[15m]))*100"
    }
   ]
  }
 ]
}