{
 "title": "Observability Workshop",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "cloudwatch" },
   { "name": "awsregion", "label": "Region", "query": "regions()" },
   {
    "name": "ekscluster",
    "label": "EKSCluster",
    "query": "resource_arns($awsregion,eks:nodegroup,{\"Workshop\":[\"true\"]})"
   },
   {
    "name": "ecsclusterlist",
    "label": "ECSClusterList",
    "query": "resource_arns($awsregion,ecs:cluster,{\"Workshop\":[\"true\"]})"
   },
   {
    "name": "ecstasklist",
    "label": "ECSTaskList",
    "query": "resource_arns($awsregion,ecs:task-definition,{\"Workshop\":[\"true\"]})"
   },
   {
    "name": "rdsclusterlist",
    "label": "RDSClusterList",
    "query": "resource_arns($awsregion,rds:cluster,{\"Workshop\":[\"true\"]})"
   },
   {
    "name": "apigwlist",
    "label": "APIGWList",
    "query": "dimension_values($awsregion,AWS/ApiGateway,Latency,ApiName)"
   },
   {
    "name": "sqslist",
    "label": "SQSList",
    "query": "resource_arns($awsregion,sqs,{\"Workshop\":[\"true\"]})"
   },
   {
    "name": "steplambdalist",
    "label": "StepLambdaList",
    "query": "resource_arns($awsregion,lambda:function,{\"Workshop\":[\"true\"]})"
   }
  ]
 },
 "panels": [
  { "title": "EKS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$ekscluster", "NodeName": "*" },
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Node Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$ekscluster", "NodeName": "*" },
     "metricName": "node_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Node File Systems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$ekscluster", "NodeName": "*" },
     "metricName": "node_filesystem_utilization",
     "namespace": "ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Pod Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$ekscluster", "PodName": "*" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "ECS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cluster CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ClusterName}}",
     "dimensions": { "ClusterName": "$ecsclusterlist" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Cluster Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "{{ClusterName}}",
     "dimensions": { "ClusterName": "$ecsclusterlist" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Task CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{TaskDefinitionFamily}}",
     "dimensions": { "TaskDefinitionFamily": "$ecstasklist" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Task Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "{{TaskDefinitionFamily}}",
     "dimensions": { "TaskDefinitionFamily": "$ecstasklist" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RDS Cluster CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{DBClusterIdentifier}}",
     "dimensions": { "DBClusterIdentifier": "$rdsclusterlist" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{DBClusterIdentifier}}",
     "dimensions": { "DBClusterIdentifier": "$rdsclusterlist" },
     "metricName": "CommitLatency",
     "namespace": "AWS/RDS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DynamoDB Table - Percent RCU Consumed",
   "type": "graph",
   "description": "Shows the consumed RCUs vs the Provisioned RCUs as a percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expression": "100*($CRCU / $PRCU)", "type": "math" }
   ]
  },
  {
   "title": "DynamoDB Table - Consumed WCU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{TableName}}",
     "dimensions": { "TableName": "*" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{ApiName}}",
     "dimensions": { "ApiName": "$apigwlist" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Integration Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{ApiName}}",
     "dimensions": { "ApiName": "$apigwlist" },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Number of Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{QueueName}}",
     "dimensions": { "QueueName": "$sqslist" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Sent Message Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{QueueName}}",
     "dimensions": { "QueueName": "$sqslist" },
     "metricName": "SentMessageSize",
     "namespace": "AWS/SQS",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Step Function Lambdas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{FunctionName}}",
     "dimensions": { "FunctionName": "$steplambdalist" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Step Function Lambdas",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{FunctionName}}",
     "dimensions": { "FunctionName": "$steplambdalist" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "region": "$awsregion",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}