name: Security Scan
permissions:
    contents: read
on:
    push:
    workflow_dispatch:

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: snyk/actions/setup@master
    ash:
        uses: ./.github/workflows/run-ash-security-scan.yaml
        permissions:
            #checkov:skip=CKV2_GHA_1:The permissions are not set to write-all at the top-level, or any level
            contents: read # Required to read the repository contents in order to scan them with ASH
            checks: write # Required for writing CI check runs
            pull-requests: write # Required for writing comments with scan results to pull requests
            #security-events: write # Required for collection of SARIF code scanning results for GitHub Advanced Security checks
        with:
            ash-version: v3.0.0-beta
            repository-owner: ${{ github.repository_owner }}
            ash-args: '--inspect'
            fail-on-findings: false
            collect-junit-xml-report: true
            collect-sarif-report: false
            post-pr-comment: true
            verbose: true
            python-version: '3.12'
            ash-mode: local
            output-dir: '.ash/ash_output'
            config: '.ash/.ash.yaml'
